name: Deploy Node.js App to Azure VM

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

env:
  APP_PORT: 3000
  APP_NAME: zainab-frontendapp
  VM_USER: azureuser
  VM_PATH: /opt/zainab-frontendapp
  NODE_VERSION: 22

jobs:
  build-package-deploy:
    runs-on: ubuntu-latest
    environment: dev   # <-- هنا نستخدم environment dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test --if-present

      - name: Package app
        run: |
          TIMESTAMP=$(date +%s)
          zip -r /tmp/${{ env.APP_NAME }}-${TIMESTAMP}.zip . -x ".git/*" "node_modules/*"

      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload ZIP to Blob
        run: |
          TIMESTAMP=$(date +%s)
          az storage blob upload \
            --account-name ${{ secrets.AZ_STORAGE_ACCOUNT }} \
            --container-name ${{ secrets.AZ_STORAGE_CONTAINER }} \
            --name ${{ env.APP_NAME }}-${TIMESTAMP}.zip \
            --file /tmp/${{ env.APP_NAME }}-${TIMESTAMP}.zip

          SAS_URL=$(az storage blob generate-sas \
            --account-name ${{ secrets.AZ_STORAGE_ACCOUNT }} \
            --container-name ${{ secrets.AZ_STORAGE_CONTAINER }} \
            --name ${{ env.APP_NAME }}-${TIMESTAMP}.zip \
            --permissions r \
            --expiry $(date -u -d "1 hour" '+%Y-%m-%dT%H:%MZ') \
            --https-only \
            --full-uri)

          echo "PACKAGE_SAS_URL=$SAS_URL" >> $GITHUB_ENV

      - name: Deploy to VM using Run Command
        run: |
          az vm run-command invoke \
            -g ${{ secrets.AZURE_RESOURCE_GROUP }} \
            -n ${{ secrets.AZURE_VM_NAME }} \
            --command-id RunShellScript \
            --scripts "
            mkdir -p $VM_PATH/releases &&
            TIMESTAMP=$(date +%s) &&
            cd $VM_PATH/releases &&
            curl -L ${{ env.PACKAGE_SAS_URL }} -o $APP_NAME-\$TIMESTAMP.zip &&
            unzip -o $APP_NAME-\$TIMESTAMP.zip -d \$TIMESTAMP &&
            ln -sfn \$TIMESTAMP $VM_PATH/current &&
            cd $VM_PATH/current &&
            curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash - &&
            sudo apt-get install -y nodejs unzip pm2 &&
            npm ci --omit=dev
          "

